[project]
name = "helion-puzzles"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "helion>=0.2.0",
    "numpy>=2.3.4",
    "torch>=2.9.0",
    "triton>=3.5.0",
]
